# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classList',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=12)),
                ('studentNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('coursesId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('coursesName', models.CharField(max_length=40)),
                ('coursesTime', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('gradeId', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('coursesId', models.ForeignKey(db_column='coursesId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.courses')),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('majorId', models.AutoField(primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=50)),
                ('collegeId', models.ForeignKey(db_column='collegeId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.college')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=10)),
                ('studentCourses', models.IntegerField()),
                ('studentSex', models.BooleanField(default=0)),
                ('classId', models.ForeignKey(db_column='classId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.classList')),
                ('collegeId', models.ForeignKey(db_column='collegeId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.college')),
                ('coursesId', models.ManyToManyField(db_column='coursesId', to='teaManaSys.courses')),
                ('majorId', models.ForeignKey(db_column='majorId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.major')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacherId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=10)),
                ('teacherSex', models.BooleanField(default=0)),
                ('teacherTitle', models.CharField(max_length=20)),
                ('collegeId', models.ForeignKey(db_column='collegeId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.college')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('uerName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='studentId',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.student'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacherId',
            field=models.ForeignKey(db_column='teacherId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.teacher'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='collegeId',
            field=models.ForeignKey(db_column='collegeId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.college'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='majorId',
            field=models.ForeignKey(db_column='majorId', on_delete=django.db.models.deletion.CASCADE, to='teaManaSys.major'),
        ),
    ]
