# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaManaSys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uerName',
            new_name='userName',
        ),
    ]
