# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaManaSys', '0002_auto_20171223_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
